- block:
  - name: Install GNOME Desktop
    shell: yum groupinstall -y 'Server with GUI'
    when: os_desktop=="gnome" and ansible_distribution != 'Amazon'

  - name: Install KDE Desktop
    shell: |
      yum groupinstall -y "X Window System"
      yum groupinstall -y "KDE"
    when: os_desktop=="kde" and ansible_distribution != 'Amazon'

  - name: Install Xfce Desktop
    shell: yum groupinstall -y 'Xfce'
    
  - name: Install Mate Desktop on AmazonLinux
    shell: |
      sudo amazon-linux-extras install -y mate-desktop1.x
      sudo bash -c 'echo PREFERRED=/usr/bin/mate-session > /etc/sysconfig/desktop'
    when: os_desktop=="mate" and ansible_distribution == 'Amazon'

  when: ansible_os_family == "RedHat"

- block:
  - name: Install GNOME Desktop
    shell: |
      apt install gnome -y
    when: os_desktop=="gnome"

  - name: Install KDE Desktop
    shell: |
      apt install tasksel
      tasksel install kubuntu-desktop
      apt install sddm
    when: os_desktop=="kde"
    
  - name: Install Xfce Desktop
    shell: |
      apt install -y xfce4 xfce4-goodies
    when: os_desktop=="xfce"

  when: ansible_os_family == "Debian"


- name: Config Desktop
  shell: |
    systemctl set-default graphical.target
    systemctl isolate graphical.target
    systemctl get-default

- name: Install VNC
  include: vnc.yml
