- name: Is cloud-init exists
  shell: ls /etc/cloud/cloud.cfg
  ignore_errors: True
  register: result

- debug: var=result.stdout

- name: Install cloud-init
  shell: |
    yum install cloud-init
  when: result.stdout != '/etc/cloud/cloud.cfg'
  
- name: Configure nginx php.conf
  template:
    src: cloud-init.cfg.j2
    dest: /etc/cloud/cloud.cfg

- name: chrony need to re-install because of service error
  shell: |
    yum erase chrony
    yum install chrony -y
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == "8"

- name: chronyd need to re-install because of service error
  shell: |
    yum erase chronyd
    yum install chronyd -y
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == "7"
  
- name: Configure time zone
  shell: |
    timedatectl set-ntp yes
    timedatectl set-timezone "Asia/Shanghai"
    timedatectl set-local-rtc yes
    systemctl restart chronyd
    hwclock --localtime
    rm -rf /etc/cloud/cloud.cfg.d/10_updates_policy.cfg
    rm -rf /etc/cloud/cloud.cfg.d/10-azure-kvp.cfg
    
- name: Change PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "PasswordAuthentication no"
    line: "PasswordAuthentication yes"

- name: Set enable login by root
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "#PermitRootLogin yes"
    line: "PermitRootLogin yes"

- name: Restart sshd
  shell: systemctl restart sshd

- include: "migration/{{os_cloudplatform}}.yml"
