- name: Is cloud-init exists
  shell: ls /etc/cloud/cloud.cfg
  ignore_errors: True
  register: result

- debug: var=result.stdout

- name: Install cloud-init
  shell: |
    yum install cloud-init
  when: result.stdout != '/etc/cloud/cloud.cfg'
  
- name: Configure nginx php.conf
  template:
    src: cloud-init.cfg.j2
    dest: /etc/cloud/cloud.cfg

- name: Change PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "PasswordAuthentication no"
    line: "PasswordAuthentication yes"

- name: Set enable login by root
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "#PermitRootLogin yes"
    line: "PermitRootLogin yes"

- name: Restart sshd
  shell: systemctl restart sshd
