- name: Disable selinux and  firewalld
  shell: |
    setenforce 0
    sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux  2>&1
    systemctl stop firewalld
    systemctl disable firewalld

- name: Install package of env, .eg.virtio
  shell: |
    yum install qemu-kvm  virt-manager libvirt virt-install openssh-askpass -y

- name: Install aegis
  shell: |
    wget {{ os_aegis_download_url }} && chmod +x AliAqsInstall_64.sh && ./AliAqsInstall_64.sh sJmepE  2>/dev/null
    test -d /usr/local/aegis && bash /usr/local/aegis/aegis_install.sh 

- name: Install cloudinit
  shell: |
    wget {{ os_cloudinit_download_url }}
    tar -zxvf ./cloud-init-*.tgz
    cd cloud-init-*
    [[ -f /usr/bin/pip-3 ]] && python3 -m pip install --upgrade pip
    [[ -f /usr/bin/pip-3 ]] && ln -sf /usr/bin/pip-3 /usr/bin/pip3
    pip3 >>test.txt
    pip3 install -r ./requirements.txt
    echo "2" >>test.txt
    cd ./tools
    echo {{ansible_distribution_major_version}} >>test.txt
    bash deploy.sh centos {{ansible_distribution_major_version}} >>test.txt

- name: Change PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "PasswordAuthentication no"
    line: "PasswordAuthentication yes"

- name: Set enable login by root
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "#PermitRootLogin yes"
    line: "PermitRootLogin yes"
