- name: Install Desktop on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Install Desktop and VNC
  include: desktop.yml
  when: os_desktop is defined and os_desktop is not none and os_desktop !="" and (os_image =="" or os_image is undefined)

- name: Make a private image with some cloud platform
  include: image.yml
  when: os_cloudplatform is defined and os_cloudplatform is not none and os_image !=""
