- block:
  - name: Install Desktop
    shell: yum groupinstall -y 'Server with GUI'

  - name: Config Desktop
    shell: |
      systemctl set-default graphical.target
      systemctl isolate graphical.target
      systemctl get-default
  when: os_gui=="gnome"

- block: 
  - name: Install VNC Server
    yum:
      name: [tigervnc-server,tigervnc-server-module]

  - name: clean
    shell: rm -rf /root/.vnc

  - name: vnc password
    expect:
      command: vncserver
      responses:
        "password": "websoft9"
        "Verify": "websoft9"
        "view-only": "n"
  
  - name: vnc service config
    copy:
      src: vncserver.service
      dest: /etc/systemd/system/vncserver@:1.service

  - name: VNC Server Start
    service:
      name: vncserver@:1.service
      enabled: yes
      state: started
      
  when: os_connection == 'vnc'
